### ISSUE TITLE
Feature request: Allow to convert back dict to string

### ISSUE THREAD

**Issue by sharpyy** [Colin-b/keepachangelog#11]
Hey Colin,

I started to use your project and I really like it. I think it would be very useful to add a to_str function in order to convert back a changelog dict to a string keeping the valid keepalog format.

The only prereq may be to start using OrderedDict in order to not loose the order of changes if adding/removing changes when updating the dict object.

Example:

```python
import keepachangelog

changes = keepachangelog.to_dict("path/to/CHANGELOG.md")

## Add new changes here
changes.add(....)

with open("path/to/CHANGELOG.md", "w") as file: 
    file.write(keepachangelog.to_str(changes)) 
```

What do you think?

Etienne

**Comment by Colin-b** [comment]
Hello Étienne,

This is a nice idea indeed I can see the appeal.
It will maybe needs some more tweaking to retrieve original formatting but we can always enhance it afterwards.

Do you want to come up with a pull request? I am under quite a bit of load for now so I may not be able to release something before August.

**Comment by sharpyy** [comment]
Hi Colin,

No rush for it. I think it will be a really useful feature to get more adoption of your module.

For now, I have made it work on my side by updating the dict to an ordereddict and creating my own to_str function which I can share:

```python
...
    with tempfile.NamedTemporaryFile() as temp:
        temp.write(changelog_file.decoded_content)
        temp.flush()
        changelog_content = OrderedDict(keepachangelog.to_dict(temp.name))
    changelog_content[version] = {
        "changed": [
            comment
        ],
        "release_date": datetime.today().strftime('%Y-%m-%d'),
        "version": version,
    }
    changelog_content.move_to_end(version, last=False)
    new_changelog = get_changelog_from_dict(changelog_content)
...

def get_changelog_from_dict(content):
    changelog = """# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""
    categories = {v: k for k, v in keepachangelog._changelog.categories.items()}
    for version, log in content.items():
        changelog += f"\n## [{log['version']}] - {log['release_date']}\n"
        for cat in categories:
            if cat in log:
                changelog += f"{categories[cat]}\n"
                for line in log[cat]:
                    changelog += f"- {line}"
        changelog += '\n'
    return changelog.rstrip()
```

Thanks again!

Etienne

**Comment by Colin-b** [comment]
With the addition of url from #22 this feature could be implemented without loss of information.

**Comment by Colin-b** [comment]
This feature is available on the develop branch and will be part of next release

**Comment by Colin-b** [comment]
Release 2.0.0.dev0 is now available with this change on pypi.
