### ISSUE TITLE
Allow pre-release versioning

### ISSUE THREAD

**Issue by justin-richert** [Colin-b/keepachangelog#19]
Hey Colin!

Thanks for such a great project! I've been hunting for something like this over the last couple of days and was pleased to find this package.

I noticed that you (very reasonably) made the decision to only support non-pre-release semantic versioning but not to allow any pre-release information on the end of the version. I've got a project that is considered to be in beta, and although the changelog parsing works just fine, the `changelog.release("CHANGELOG.md")` command errors out due to the most recent version having `bXX` on the end of it which causes it to be considered an invalid version.

How would you feel about allowing pre-release matching and just bumping the pre-release number (e.g. `b1`->`b2`)? I do realize that this probably opens the door to a whole slew of cases, but perhaps we could systematically support more and just be explicit about what is and isn't handled. Then others can open issues as needed instead of trying to solve the whole scope of problems at once :)

Another option that doesn't _quite_ solve the same issue but would perhaps at least be a good intermediate step would be to allow the passing of the desired version to the `.release` function. If you don't like that because it allows people to abuse SemVer, I get that too.

Anyway, let me know what you think! I think this project is small enough that I could get familiarized with it somewhat quickly and contribute an attempt at this if you'd like.

**Comment by Colin-b** [comment]
Hello @justin-richert ,

Can you provide a sample of markdown content so that I can reproduce it and see what we can do from here?

Thanks again

**Comment by justin-richert** [comment]
Sure!

```markdown
# Changelog
All notable changes to this project will be documened in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

## [2.5.0b52] - 2021-04-21
### Changed
- Default Vary header now set on all responses for aiohttp apps
- ETag header logic for collection responses updated to indicate weak ETags

## [2.5.0b51] - 2021-04-21
### Fixed
- nginx container health check route in aiohttp kube deployment yaml was incorrect
```

This is probably a little bit of a bad example. I did go to semver.org and saw that the format defined there is actually this: `1.0.0-beta.1` instead of the way I have it. I think I pulled my formatting from PyPI's documentation, but I'm pretty sure their implementation is flexible enough to handle things like `1.0.0-beta.1` instead if you prefer to go the formal SemVer route.

Let me know if I can be of any help!

**Comment by Colin-b** [comment]
@justin-richert there is no way we can properly automate bumping pre-release or release metadata information. As it is up to the user. In your case indeed it's easy to handle as you are incrementing an integer, but semver could also be used in the pre-release information as in X.Y.Z-dev.A.B.C. So I would rather avoid opening this door.

New version will however handle this kind of version and by default bump to a stable version.

If you want to be able to bump to a specific non-stable version, then I will add the ability to provide the new version yourself.
You would then be able to implement your own logic by:

1. Retrieving latest version (2.5.0b52 in your case)
2. Bumping pre-release to 53 by incrementing it (as it will be available in the semantic_version dict that will be introduced in #24 )
3. Provide this new version to the `release` function.

I think this will cover all possible use case and still keep the project maintainable enough :)

**Comment by Colin-b** [comment]
This is now in develop branch and will be part of next release

**Comment by justin-richert** [comment]
@Colin-b Awesome. I think this is a perfect and simple solution. Thanks for spending time thinking about the problem and developing a solution for it. I appreciate your time!
