### ISSUE TITLE
A dict in python is not ordered

### ISSUE THREAD

**Issue by Gustry** [Colin-b/keepachangelog#21]
Following the documentation :  

https://github.com/Colin-b/keepachangelog#convert-changelog-to-dict

In Python, a dict is not ordered. So to use this API, another script needs to read all versions and re-ordered them according to semantic versioning to be sure about the order.

I think it would be nice to either change to a list, which is ordered and provided "indexing" for accessing members or switch to https://docs.python.org/3.7/library/collections.html?highlight=ordereddict#collections.OrderedDict ?

It would make it easier to fetch the latest version changelog like : 

```python
changes = keepachangelog.parse("path/to/CHANGELOG.md")
latest = changes[0]  # Get the latest version described in the file
```

**Comment by Colin-b** [comment]
Since python 3.6, dicts are ordered in python (it was already the case since 3.5 but there was no "official" support). The resulting dict will match the order of releases in the changelog.

Do you mean that you want the releases to be re-ordered and not follow changelog order?

**Comment by Gustry** [comment]
Whaou, I missed that info when I switched from Python 2.
Thanks for the information.
