### ISSUE TITLE
Add url to a release

### ISSUE THREAD

**Issue by Gustry** [Colin-b/keepachangelog#22]
First, thanks to this parser. It looks promising and needed ;-)

For a given version, there is some properties already provided `version`, `release_date`.
It would be nice to add some more : 
* `url` if described in the markdown file. For now, you need to parse again the file to find it in another script.
* `is_pre_release` if the version name contains any pre release string : https://semver.org/

> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

The last point can be easily detected by a third party script I agree, it's just to make it all in one ;-)

**Comment by Colin-b** [comment]
I splitted it in 2 tickets, the one for semantic details is #24

**Comment by Colin-b** [comment]
url is already implemented in dev and will be part of 1.0.0 release.

**Comment by Gustry** [comment]
Great thanks.

I will have a look soon.
