### ISSUE TITLE
0.5.0 is breaking retro-compatibility

### ISSUE THREAD

**Issue by aogier** [Colin-b/keepachangelog#23]
Hi, I'd like to point out that switching "unreleased" casing breaks in facts retrocompatibility w/ previous versions, I'm maintaining a tool which manipulate changelogs and this breaks a lot of tests https://travis-ci.org/github/aogier/chachacha/jobs/767594962
Not a biggie, I will fix them, but I encourage you to reconsider your future versioning and adopt a proper semantic versioning

thanks and keep up the good work!

**Comment by Colin-b** [comment]
Hello @aogier ,

According to semantic versioning, if the major is 0, then all minor bump can be breaking changes and this is a behavior that you will find quite often.

However you are absolutely right to request stability between releases. This is why next version will be `1.0.0` as API should not change that much now :)

Best Regards
