### ISSUE TITLE
"to_raw_dict" doesn't not include "Unreleased"

### ISSUE THREAD

**Issue by Gustry** [Colin-b/keepachangelog#35]
I think in the function `to_raw_dict`, there isn't any option to add the `## Unreleased` section.

It's possible in other function with `show_unreleased=True`.

**Comment by Colin-b** [comment]
As I did not had a use case for it, I figured it could be added on demand when needed. I will see if I can spare some time next week to add this :)

**Comment by Gustry** [comment]
Well, it's alright. I just noticed it, but I actually don't need it now.

**Comment by Colin-b** [comment]
Oh alright, then I would rather not introduce code that has no usage if that's ok. Can I let you close the ticket?
