### ISSUE TITLE
to_dict does not allow to provide a custom encoding

### ISSUE THREAD

**Issue by 665465** [Colin-b/keepachangelog#39]
I get a **UnicodeDecodeError** saying **"'gbk' codec can't decode byte 0xaf in position 187: illegal multibyte sequence".**
I have to specify the encoding in  _changelog.py file to make it work.
Consider adding a encoding parameter to the to_dict  method?
![image](https://user-images.githubusercontent.com/3960822/190307104-827f6e74-550a-4a58-8469-a5fd187b5a5d.png)

**Comment by Colin-b** [comment]
Hi @665465 , 

Indeed it would make sense to be able to support characters that are not supported by the platform you are running your code on.

Would you mind coming up with a pull request for this?
Only for the to_dict function for now if possible :)

Thanks again

**Comment by 665465** [comment]
The reason for this problem is that the default encoding python used is based on locale.
For example python would use 'gbk' as encoding if I don't specify encoding but my docs are encoded with 'utf-8'.
Python 3.15 change the behavior and make 'utf-8' default. [https://peps.python.org/pep-0686/](url)
Therefore it would be reasonable to add a encoding argument and make to default to 'utf-8'?
[https://github.com/Colin-b/keepachangelog/pull/43](url)

**Comment by 665465** [comment]
a workaround without changing the source code could be setting the default encoding to 'utf-8' temporarily
`sys.stdin = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8')`

**Comment by Colin-b** [comment]
Release 2.0.0.dev4 is now available on pypi and should fix this issue
