### ISSUE TITLE
How can I retrieve latest version on pypi?

### ISSUE THREAD

**Issue by solaris187** [Colin-b/keepachangelog#46]
Pypi only appears to have packages for version 1.0.0. Do you intend on publishing v2.0.0 to pypi as well?

**Comment by Colin-b** [comment]
Hello @solaris187 

They are on pypi. but not as stable version. You can specify the explicit version when installing, or using the [--pre](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-pre) argument with pip.

I plan on switching to stable at some point once there are no more breaking changes foreseen :)
