### ISSUE TITLE
you're now a dependency! :)

### ISSUE THREAD

**Issue by aogier** [Colin-b/keepachangelog#6]
Ciao, this is just to let you know this project is now a dependency on my latest project [chachacha](https://github.com/aogier/chachacha), where I'm trying to implement a generic plugin-based changelog editing tool and other whistles that will come. Thank you for your work, ciao!

**Comment by Colin-b** [comment]
That's nice to hear :-)
 If you want some more features please don't hesitate to ask or even propose changes :-)
