### ISSUE TITLE
0.3.0: asterisks should only be stripped from the left

### ISSUE THREAD

**Issue by ewen-lbh** [Colin-b/keepachangelog#9]
If a changelog entry ends with italics, eg:

```markdown
### Changed

- Lorem ipsum dolor sit *amet*
```

Then the parsed entry would be:

```json
"changed": [
    "Lorem ipsum dolor sit *amet"
]
```

Which seems invalid to me.

A one-character change in `_changelog.py` fixes this problem:

```diff
- line.strip(" -*")
+ line.lstrip(" -*")
```

I can do a PR too, but since this change is so quick, It'll be easier if @Colin-b can do it.

**Comment by Colin-b** [comment]
Release 0.3.1 is now available in pypi
